Repository DOLBOMI/DOLBOMI_FRONT, pull requests merged in 2021-07, with the labels that each got.

#2 [#1] 프로젝트 생성
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/dolbomi/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dolbomi/MainActivity.java
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/example/dolbomi/ExampleUnitTest.java
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: initialize

#5 [#3] 로그인/회원가입 화면
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dolbomi/LoginActivity.java
  app/src/main/java/com/example/dolbomi/MainActivity.java
  app/src/main/java/com/example/dolbomi/RegisterActivity.java
  app/src/main/res/drawable/rounded_edittext.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: feature

#10 [#4] 센서 관리 화면
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dolbomi/MainActivity.java
  app/src/main/java/com/example/dolbomi/SensorActivity.java
  app/src/main/res/drawable/bathtub_icon.png
  app/src/main/res/drawable/bed_round.png
  app/src/main/res/drawable/door_icon.jpg
  app/src/main/res/drawable/fridge_icon.png
  app/src/main/res/drawable/ic_baseline_contactless_24.xml
  app/src/main/res/drawable/ic_baseline_menu_24.xml
  app/src/main/res/drawable/ic_baseline_single_bed_24.xml
  app/src/main/res/drawable/pill_icon.jpg
  app/src/main/res/drawable/round_rectangle.xml
  app/src/main/res/layout/activity_sensor.xml
  app/src/main/res/layout/toolbar.xml
  app/src/main/res/menu/menu_toolbar.xml
  app/src/main/res/values/style.xml
Labels: feature

#8 [#6] 홈 상태 화면
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dolbomi/HomeStatus.java
  app/src/main/java/com/example/dolbomi/MainActivity.java
  app/src/main/res/layout/status_home.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: feature

#9 [#7] 홈 메인 생성
  .idea/.name
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_menu-playstore.png
  app/src/main/java/com/example/dolbomi/IntroActivity.java
  app/src/main/java/com/example/dolbomi/IntroThread.java
  app/src/main/java/com/example/dolbomi/MainActivity.java
  app/src/main/res/drawable/dolbomi.png
  app/src/main/res/drawable/ic_menu_background.xml
  app/src/main/res/drawable/menu.png
  app/src/main/res/drawable/phone.png
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/actionbar_actions.xml
  app/src/main/res/mipmap-anydpi-v26/ic_menu.xml
  app/src/main/res/mipmap-anydpi-v26/ic_menu_round.xml
  app/src/main/res/mipmap-hdpi/ic_menu.png
  app/src/main/res/mipmap-hdpi/ic_menu_foreground.png
  app/src/main/res/mipmap-hdpi/ic_menu_round.png
  app/src/main/res/mipmap-mdpi/ic_menu.png
  app/src/main/res/mipmap-mdpi/ic_menu_foreground.png
  app/src/main/res/mipmap-mdpi/ic_menu_round.png
  app/src/main/res/mipmap-xhdpi/ic_menu.png
  app/src/main/res/mipmap-xhdpi/ic_menu_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_menu_round.png
  app/src/main/res/mipmap-xxhdpi/ic_menu.png
  app/src/main/res/mipmap-xxhdpi/ic_menu_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_menu_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_menu.png
  app/src/main/res/mipmap-xxxhdpi/ic_menu_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_menu_round.png
  app/src/main/res/values/themes.xml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#20 [#13] 관리자 모드 메인 페이지
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dolbomi/AdminMode.java
  app/src/main/java/com/example/dolbomi/ChangeStatus.java
  app/src/main/res/drawable/round_user.xml
  app/src/main/res/layout/activity_admin_mode.xml
  app/src/main/res/layout/activity_change_status.xml
  app/src/main/res/menu/menu_toolbar.xml
  app/src/main/res/values/colors.xml
Labels: feature

#23 [#14] 태그 기록 페이지
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dolbomi/DatePickerFragment.java
  app/src/main/java/com/example/dolbomi/TagHistory.java
  app/src/main/res/drawable-v24/all_d_64.png
  app/src/main/res/drawable-v24/all_w_64.png
  app/src/main/res/drawable-v24/bed_64.png
  app/src/main/res/drawable-v24/beds_64.png
  app/src/main/res/drawable-v24/calendar64.png
  app/src/main/res/drawable-v24/date32.png
  app/src/main/res/drawable-v24/lavatory_64.png
  app/src/main/res/drawable-v24/pill_64.png
  app/src/main/res/drawable-v24/refrigerator_64.png
  app/src/main/res/drawable-v24/smart_refrigerator_64.png
  app/src/main/res/layout/activity_tag_history.xml
  app/src/main/res/layout/fragment_date_picker.xml
  app/src/main/res/values/strings.xml
Labels: feature

#21 [#12] 운동 상세 데이터 화면
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dolbomi/ExerciseDetail.java
  app/src/main/java/com/example/dolbomi/paging/DivisionPageType.java
  app/src/main/java/com/example/dolbomi/paging/LakuePagingButton.java
  app/src/main/java/com/example/dolbomi/paging/OnPageSelectListener.java
  app/src/main/java/com/example/dolbomi/paging/PagingDefine.java
  app/src/main/res/layout/activity_exercise_detail.xml
  app/src/main/res/values/colors.xml
  build.gradle
Labels: feature

#18 [#15] 생활 패턴 페이지
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dolbomi/IntroActivity.java
  app/src/main/java/com/example/dolbomi/LifePatternActivity.java
  app/src/main/res/drawable/custom_progress_bar.xml
  app/src/main/res/drawable/day_button.xml
  app/src/main/res/drawable/rounded_button.xml
  app/src/main/res/layout/activity_life_pattern.xml
  app/src/main/res/values/colors.xml
Labels: feature

#24 [#22] 페이지 연결
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dolbomi/CallActivity.java
  app/src/main/java/com/example/dolbomi/HomeStatus.java
  app/src/main/java/com/example/dolbomi/MainActivity.java
  app/src/main/res/drawable-v24/phone_w2_24.png
  app/src/main/res/drawable-v24/phone_w_24.png
  app/src/main/res/drawable/gas.png
  app/src/main/res/drawable/humidity.png
  app/src/main/res/drawable/temperature.png
  app/src/main/res/layout/activity_call.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/status_home.xml
  app/src/main/res/menu/main_toolbar.xml
Labels: feature, ing

#26 [#25] firebase 연동
  .gitignore
  .idea/misc.xml
  app/build.gradle
  build.gradle
Labels: feature
